language: android
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
    - add-on
    - extra

env: 
    - PROJECT="QuizCompose"

script:
    - cd $PROJECT
    - ./gradlew build connectedCheck
    - cd ..
